### PR TITLE
PR To go over latest changes made to SWA Hackathon

### PR DESCRIPTION
**Pull request by ghost**
@byrcyb can you please go over the notebooks

[Labour force characteristics in S. Alberta](https://github.com/callysto/hackathon/tree/Southwestern-Alberta-Open-Data/Southwestern-Alberta-Open-Data/Lethbridge-Stats-Can-Data/Census_Data_Notebooks/labour-force) 
and 
[Getting to work data in S. Alberta](https://github.com/callysto/hackathon/blob/Southwestern-Alberta-Open-Data/Southwestern-Alberta-Open-Data/Lethbridge-Stats-Can-Data/Census_Data_Notebooks/place-commute-work/place-commute-work.ipynb)

### CODE REVIEW

**Comment by ghost** [comment]
If it looks good, we then need to think about a narrative, and add exercises. 
There is a lot of data to explore, so my current idea is to ask the students to complete a few lines of code, but have most of the focus on exploring the data and determining what the differences and similarities are between and within the cities.

**Comment by ghost** [comment]
@byrcyb  changed focus of notebook and refactored so that it is compatible with colab
[Getting to work](https://github.com/callysto/hackathon/blob/Southwestern-Alberta-Open-Data/Southwestern-Alberta-Open-Data/Lethbridge-Stats-Can-Data/Census_Data_Notebooks/place-commute-work/place-commute-work.ipynb)

Can you please revise?

**Comment by ghost** [comment]
@misterhay  I stole your pencil icon ✏️ I think it's great :)
Could you please take a look? Adding you as reviewer.

**Comment by byrcyb** [comment]
Both @misterhay and I have reviewed and added in our edits so it's good to merge.

**Comment by ghost** [comment]
Awesome. Thank you @misterhay  and @byrcyb 
Merging.

**Pull request merged**
